[package]
name = "newagt-core"
version = "0.1.0"
description = "Imagery ground truth AGT parser library"
readme = "../../README.md"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
